# Generated by Django 5.1.1 on 2024-11-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_carrito_pedidos_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
            preserve_default=False,
        ),
    ]
