# Generated by Django 5.1.1 on 2024-11-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_carrito_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('table', 'producto')},
        ),
    ]
