# Generated by Django 5.1.1 on 2024-11-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_carrito_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tables.category'),
            preserve_default=False,
        ),
    ]
