# Generated by Django 5.1.1 on 2024-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_category_product_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=models.SET('Categoria eliminada'), to='tables.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
