# Generated by Django 5.1.1 on 2024-11-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_category_nombre_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
