# Generated by Django 5.1.1 on 2024-11-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_carrito_atendido_carrito_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.JSONField(default=dict),
        ),
    ]
