# Generated by Django 5.1.1 on 2024-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_alter_carrito_unique_together_product_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
